# Use the official Golang image as base image
FROM golang:alpine AS builder

# Set the current working directory inside the container
WORKDIR /app

# Copy the Go modules and their dependencies
COPY go.mod ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source code into the container
COPY . .

# Build the Go app
RUN go build -o main .

# Start a new stage from scratch
FROM alpine

# Set the working directory in the container
WORKDIR /app

# Copy the pre-built binary file from the previous stage
COPY --from=builder /app/main .

# Expose port 8080 to the outside world
EXPOSE 8585

# Command to run the executable
CMD ["./main"]
