services:
  services:
    build:
      context: .
      dockerfile: dockerfile_Services
      args:
        - level=services
    volumes:
      - ./root_ca_f:/root_ca
      - ./certs_users:/certs_users

  users:
    build:
      context: .
      dockerfile: dockerfile_Users
      args:
        - level=users
    volumes:
      - ./root_ca_f:/root_ca
      - ./certs_services:/certs_services
  
  nginx:
    image: nginx:latest
    ports:
      - 5001:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../../CA:/etc/nginx/ca
