FROM python

WORKDIR /usr/src/app

# Copying requirements and installing dependencies
RUN pwd
COPY . .
RUN pip install --no-cache-dir -r requirements.txt

# Copying the rest of the application
COPY . .

ENV FLASK_APP=endpoint.py

RUN pip install Flask

EXPOSE 5000

CMD python3 endpoint.py sub_ca_users.key sub_ca_users.crt sub_ca_users.crl /certs_users
