services:
  nginx:
    image: nginx:latest
    ports:
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../CA:/etc/nginx/ca
      - ./ssl:/etc/nginx/ssl
  endpoint:
    build: ./app
    volumes:
      - /home/edu/MEI/SEGPRD/SEGPRD_T2/CA/certs:/home/ca

