services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../CA:/etc/nginx/ca
      - ./ssl:/etc/nginx/ssl
  endpoint:
    build: ./app
    
    volumes:
    - ../CA:/home/ca
    ports:
      - 8585:8585